config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }

  resources :messages, only: %i[create]
  get '/messages/new/:id', to: 'messages#new', as: 'new_message'

  authenticate :user do
    get 'new_category', to: 'categories#new', as: 'new_category'
    get 'messages/inbox', to: 'messages#index', as: 'inbox'
    get 'messages/outbox', to: 'messages#index_outbox', as: 'outbox'
    resources :items, only: %i[new create edit update destroy] do
      member do
        patch 'sold'
        patch 'unsold'
      end
    end
    resources :messages, only: %i[index]
    resources :users, only: %i[index]
    patch 'users/:id', to: 'users#change', as: 'admin_change_user'
    resources :categories, only: %i[create]
  end

  resources :items, only: %i[index show]

  resources :messages, only: %i[show]
  resources :categories, only: %i[index], as: 'categories'

  # get 'users/:id', to: 'users#show', as: 'user'

  resources :users, only: %i[show] do
    member do
      patch 'ban'
      patch 'unban'
      patch 'admin'
    end
  end
  get '/categories/*path', to: 'categories#categ_index', param: :path

  root 'items#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :trackable,
         :omniauthable, omniauth_providers: [:vkontakte]

  has_many :items, dependent: :destroy

  has_many :sent_private_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_private_messages, class_name: 'Message', foreign_key: 'receiver_id'

  def self.find_for_vkontakte_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.remote_avatar_url = auth.info.image
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :admin_user, only: %i[destroy change index ban unban admin]

  def show
    @user = User.includes(:items).find(params[:id])
    if  (params[:active_page].nil? && params[:finished_page].nil?)
      @active_items = @user.items.where(sold: false).order(created_at: :DESC).paginate(page: params[:active_page], per_page: 16)
      params[:active_page] = 1 if params[:active_page].nil?
      params[:active_page] =params[:active_page].to_i + 1
      @finished_items = @user.items.where(sold: true).order(created_at: :DESC).paginate(page: params[:finished_page], per_page: 16)
      params[:finished_page] = 1 if params[:finished_page].nil?
      params[:finished_page] = params[:finished_page].to_i + 1
    else
      if (params[:active_page].nil?)
        @finished_items = @user.items.where(sold: true).order(created_at: :DESC).paginate(page: params[:finished_page], per_page: 16)
        params[:finished_page] = 1 if params[:finished_page].nil?
        params[:finished_page] = params[:finished_page].to_i + 1
      else
        @active_items = @user.items.where(sold: false).order(created_at: :DESC).paginate(page: params[:active_page], per_page: 16)
        params[:active_page] = 1 if params[:active_page].nil?
        params[:active_page] = params[:active_page].to_i + 1
      end
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @users = User.all.order(created_at: :DESC).paginate(page: params[:page], per_page: 10)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'Пользователь удалён'
    redirect_to users_url
  end

  #   def update
  #     @user = User.find(params[:id])
  #     respond_to do |format|
  #       if @user.update(user_params)
  #         format.html { redirect_to @user, notice: 'Объявление успешно изменено.' }
  #         format.json { render :show, status: :ok, location: @user }
  #       else
  #         format.html { redirect_to @user, notice: 'Объявление не было успешно изменено.' }
  #         format.json { render json: @user.errors, status: :unprocessable_entity }
  #       end
  #     end
  #   end

  def ban
    @user = User.find(params[:id])
    @user.update(ban: true)
    redirect_to @user, success: 'Пользователь был забанен.'
  end

  def unban
    @user = User.find(params[:id])
    @user.update(ban: false)
    redirect_to @user, success: 'Пользователь был разбанен.'
  end

  def admin
    @user = User.find(params[:id])
    @user.update(admin: true)
    redirect_to @user, success: 'Пользователь стал администратором.'
  end

  def change
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, info: 'Изменения сохранены.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { redirect_to @user, danger: 'Не удалось сохранить изменения.' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.permit(:ban, :admin)
  end
end

app/views/users/_user.html.erb
<div>
    	  <p><%= image_tag(user.avatar.url, alt: 'avatar',class:"img-circle") if user.avatar? %></p>
        <p><h4><%=link_to user.name, user %></h4></p>
        <%= button_to 'Написать сообщение',"/messages/new/#{user.id}", method: "get", class: "btn btn-primary" %>
        <p>Зарегистрирован <%= user.created_at.strftime("%d/%m/%y") %></p>
        <p>Количество объявлений <%=user.items.size%></p>
        <% if current_user && (current_user == user || current_user.admin?) %>
         <% if current_user.admin? %>
            <% if user.ban? %>
              <%= button_to 'Разбанить', {controller: 'users', action: "change", id: user.id , ban: false }, method: :patch, data: { confirm: 'Вы уверены?'}, class: "btn btn-danger"%>
            <% else %>
              <%= button_to 'Забанить', {controller: 'users', action: "change", id: user.id , ban: true }, method: :patch, data: { confirm: 'Вы уверены?'}, class: "btn btn-danger"%>
            <% end %> 
            <% if user.admin? %>
              <p><h5>Администратор</h5></p>
            <% else %>
              <%= button_to 'Сделать админом', {controller: 'users', action: "change", id: user.id , admin: true }, method: :patch, data: { confirm: 'Вы уверены?'}, class: "btn btn-info"%>
            <% end %>
          <% end %>
        <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Все пользователи') %>
<h1>Все пользователи</h1>

<table class="table">
<% if !@users.blank? %>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td width="13%">
          <%= image_tag(user.avatar.url, alt: 'avatar', class:"img-circle") if user.avatar? %>
        </td>
        <td width="13%" style="vertical-align: middle">
          <%= link_to user.name, user %>
        </td>
        <td style="vertical-align: middle">
          <%= user.items.count %>
        </td>
        <td width="13%" style="vertical-align: middle">
          <% if user.admin? %>
             Администратор 
          <% else %>
            Пользователь 
          <% end %>
        </td>
        <td width="10%">
            <% if user.ban? %>
              <%= button_to 'Разбанить', {controller: 'users', action: "change", id: user.id , ban: false }, method: :patch, data: { confirm: 'Вы уверены?'},class: "btn btn-primary"%>
            <% else %>
              <%= button_to 'Забанить', {controller: 'users', action: "change", id: user.id , ban: true }, method: :patch, data: { confirm: 'Вы уверены?'},class: "btn btn-primary"%>
            <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
<% end %>
</table>
<div align="center">
  <%= will_paginate @users %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="container">
  <div class="row">
<aside class="col-md-3">
  <section class="user_info">
    <%= render 'user', user: @user %>
  </section>
</aside>


    <div class="col-md-9">
      <div class="tabs">
        <ul class="nav nav-tabs">
          <li  class="<%= 'active' unless params[:active_tab] == 'tab-2' %>">
            <a class="nav-link <%= 'active' unless params[:active_tab] == 'tab-2' %>" data-toggle="tab" href="#tab-1">Активные</a></li>

            <li class="<%= 'active' if params[:active_tab] == 'tab-2' %>">
              <a class="nav-link <%= 'active' if params[:active_tab] == 'tab-2' %>" data-toggle="tab" href="#tab-2">Завершённые</a></li>
            </ul>


            <div class="tab-content">

             <div class="one tab-pane fade in active"  id="tab-1">
              <% unless @active_items.blank?%>
                <div id="items1">
                  <div class="row">
                  <%= render partial: 'items/small_item', collection: @active_items, as: :item %>
                </div>
                </div>


              <div align="center">
                <div class="linkmore1">
                  <%= link_to 'Загрузить ещё', user_path(active_page: @active_items.next_page),:class => 'next1', :remote => true if @active_items.next_page %>
                </div>
              </div>
              <% else %>
              <br>
              <p>Активных объявлений не найдено.</p>
              <% end %>
            </div>

            <div class="two tab-pane fade" id="tab-2">
              <% unless @finished_items.blank?%>
                <div id="items2">
                  <div class="row">
                  <%= render partial: 'items/small_item', collection: @finished_items, as: :item %>
                </div>
              </div>



              <div align="center">
                <!--<%= will_paginate @finished_items, :param_name => 'finished_page',params: {active_tab: 'tab-2'} %>-->
                <div class="link more2">
                  <%= link_to 'Загрузить ещё', user_path(finished_page: params[:finished_page]),:class => 'next2', :remote => true if @finished_items.next_page %>

                </div>
              </div>
              <% else %>
              <br>
              <p>Объявлений не найдено.</p>
              <% end %>
            </div>




          </div>
        </div>
      </div>
    </div>
  </div>

app/views/users/show.js.erb



<% if params[:active_page].nil? %>
	$('#items2').append('<%= j render(partial: 'items/small_item', collection: @finished_items, as: :item) %>');
	<% if @finished_items.next_page %>
	$('a.next2').attr('href','<%= user_path(finished_page: params[:finished_page]) %>');
	<% else %>
	$('a.next2').remove();
	<% end %>
<% else %>
	$('#items1').append('<%= j render(partial: 'items/small_item', collection: @active_items, as: :item) %>');
	<% if @active_items.next_page %>
	$('a.next1').attr('href','<%= user_path(active_page: params[:active_page]) %>');
	<% else %>
	$('a.next1').remove();
	<% end %>
<% end %>