config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }

  resources :messages, only: %i[create]
  get '/messages/new/:id', to: 'messages#new', as: 'new_message'

  authenticate :user do
    get 'new_category', to: 'categories#new', as: 'new_category'
    get 'messages/inbox', to: 'messages#index', as: 'inbox'
    get 'messages/outbox', to: 'messages#index_outbox', as: 'outbox'
    resources :items, only: %i[new create edit update destroy] do
      member do
        patch 'sold'
        patch 'unsold'
      end
    end
    resources :messages, only: %i[index]
    resources :users, only: %i[index]
    patch 'users/:id', to: 'users#change', as: 'admin_change_user'
    resources :categories, only: %i[create]
  end

  resources :items, only: %i[index show]

  resources :messages, only: %i[show]
  resources :categories, only: %i[index], as: 'categories'

  # get 'users/:id', to: 'users#show', as: 'user'

  resources :users, only: %i[show] do
    member do
      patch 'ban'
      patch 'unban'
      patch 'admin'
    end
  end
  get '/categories/*path', to: 'categories#categ_index', param: :path

  root 'items#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  mount_uploaders :attachments, AttachmentsUploader

  belongs_to :user
  delegate :name, :price, :description, :avatar, :created_at, to: :user, prefix: true
  belongs_to :category

  validates :user_id, :price, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 140 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  def self.test_draw
    @root_category = Category.find(1)
    dashstr = '-'
    @@counter = 0
    temp = Array.new(Category.count - 1)
    @root_category.subcategories.each do |node|
      temp[@@counter] = Array.new(3)
      temp[@@counter][0] = node.id
      temp[@@counter][1] = node.name
      if node.subcategories.any?
        temp[@@counter][2] = true
        @@counter += 1
        draw_tree(node, dashstr, temp)
      else
        temp[@@counter][2] = false
        @@counter += 1
      end
    end
    temp
  end

  def self.draw_tree(category, dashstr, temp)
    category.subcategories.each do |child|
      temp[@@counter] = Array.new(3)
      temp[@@counter][0] = child.id
      temp[@@counter][1] = dashstr + child.name
      if child.subcategories.any?
        temp[@@counter][2] = true
        @@counter += 1
        draw_tree(child, dashstr + '-', temp)
      else
        temp[@@counter][2] = false
        @@counter += 1
      end
    end; nil
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :correct_user,   only: %i[edit update destroy sold unsold]
  before_action :ban_user, only: %i[new]
  before_action :set_item, only: %i[show edit update destroy sold unsold]

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(sold: false).order(created_at: :DESC).paginate(page: params[:page], per_page: 16)
  end

  # GET /items/1
  # GET /items/1.json
  def show; end

  # GET /items/new
  def new
    @item = Item.new
    @testcat = Item.test_draw
  end

  # GET /items/1/edit
  def edit
    @testcat = Item.test_draw
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params)
    @testcat = Item.test_draw
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, success: 'Объявление успешно создано.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, info: 'Объявление успешно изменено.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def sold
    @item.update(sold: true)
    redirect_to @item, info: 'Товар помечен как проданный.'
  end

  def unsold
    @item.update(sold: false)
    redirect_to @item, info: 'Товар помечен как активный'
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, info: 'Объявление удалено.' }
      format.json { head :no_content }
    end
  end

  private

  def correct_user
    @user = Item.find(params[:id]).user
    redirect_to(root_url) unless (@user == current_user) || current_user.admin?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:name, :sold, :category_id, :price, :description, :image, attachments: [])
  end

  def ban_user
    redirect_to(root_url) unless current_user && !current_user.ban?
  end
end

app/views/items/_form.html.erb
<div class="container">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: item, local: true) do |form| %>
    <% if item.errors.any? %>
    <div id="alert alert-error">
      <h2><%= t('validate_errors', count: item.errors.count) %>:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= form.label :Название %>
    <%= form.text_field :name, id: :item_name, required: true, class: 'form-control' %>




    <%= form.label :Категория %>
    <%= form.select :category_id, class: "input-group-btn" do %>
    <% testcat.each do |c| -%>
    <%= content_tag(:option, c.second, value: c.first, disabled: c.last) %>
    <% end %>
    <% end %>


    <%= form.label :Цена %>
    <%= form.number_field :price, id: :item_price,required: true, min: '0', class: 'form-control' %>



    <%= form.label :Описание %>
    <%= form.text_area :description, id: :item_description, required: true, class: 'form-control' %>


    <div align="center" style="padding: 5px">
      <label class="btn btn-primary btn-file" align="center">
        Выберите фото
        <%= form.file_field :attachments, multiple: true, required: true %>
      </label>
    </div>
    <div align="center" style="padding: 5px">
      <%= form.submit 'Создать объявление', class: "btn btn-primary" %>
    </div>

    <% end %>

  </div>
</div>
</div>

app/views/items/_item.html.erb
<div class="col-md-3">
	<a href="<%= item_url(item)%>">
	<div class="item-view">
		<% if item.attachments? %>
			<%= image_tag(item.attachments.first.thumb_index.url, alt: 'Image') %>
		<% end %>
		<div class="item-name"><%=  "#{item.name}" %></div>
		<p><%= item.price %> р.</p>
		<div class="created-date"><%= l item.created_at, format: "%d %B %k:%M"   %></div>
	</div>
</a>
</div>

app/views/items/_small_item.html.erb
<div class="col-md-3">
  <div class="small-item-view">
  <% if item.attachments? %>
  <%= link_to(image_tag(item.attachments.first.small_thumb.url, alt: 'Image'), item) %>
  <% end %>
  <div>
      <div>
          <div class="small-item-name"><%=  link_to "#{item.name}",item %></div>
          <p class="small-item"><%= item.price %> р.</p>
          <div class="created-date"><%= l item.created_at, format: "%d %B %k:%M"   %></div>
      </div>
      </div>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Изменить объявление</h1>

<%= render 'form', item: @item, testcat: @testcat %>

<div align="center">
	<%= link_to 'Показать', @item %> |
	<%= link_to 'Назад', items_path %>
</div>

app/views/items/index.html.erb
<h1>Объявления</h1>
<% unless @items.blank?%>
<div class="container">
  <div class="row">
        <%= render @items %>
  </div>
</div>
<div align="center">
 <%= will_paginate @items %>
</div>
<% else %>
<br>
<p>Объявлений не найдено.</p>
<% end %>

app/views/items/index.js.erb
$('#items').append('<%= j render(@items) %>');
<% if @items.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@items) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/items/new.html.erb
<% provide(:title, 'Новое объявление') %>
<h1>Новое объявление</h1>

<%= render 'form', item: @item, testcat: @testcat %>

app/views/items/show.html.erb
<% provide(:title, @item.name) %>
<div class="container">
<div class="row">
  <div class="col-md-6">
    <h2><%= @item.name %></h2>
    <p><%= l @item.created_at, format: "%d %B %k:%M"   %></p>
  </div>
  <div class="col-md-6" align="right">
    <h3><%= @item.price %> р.</h3>
    <% if current_user && (current_user == @item.user || current_user.admin?) %>
      <%= link_to 'Редактировать', edit_item_path(@item), class:"btn btn-link" %> 
      <% if @item.sold? %>
        <%= link_to 'Сделать активным',unsold_item_path(@item.id), method: :patch, data: { confirm: 'Вы уверены?'}, class:"btn btn-link"%>
      <% else %>
        <%= link_to 'Уже продал',sold_item_path(@item.id), method: :patch, data: { confirm: 'Вы уверены?'}, class:"btn btn-link"%>
      <% end %>
      <% else %>
      <% if @item.sold? %>
        <p>Объявление не активно</p>
      <% end %>
    <% end %>
  </div>
</div>









<div class="row">
  <% if @item.attachments? %>
  <div class="col-md-8" align="center">
    <%= image_tag(@item.attachments.first.thumb.url) %>
  </div>
  <% end %>
  <div class="col-md-4">
    <p><%=link_to @item.user_name, @item.user %></p>
    <%= button_to 'Написать сообщение',"/messages/new/#{@item.user.id}", method: "get", class: "btn btn-primary" %>
    <p>Зарегистрирован <%= l @item.user_created_at, format: "%d/%m/%y" %></p>
    <p ><%= image_tag(@item.user_avatar.url, alt: 'avatar',class:"img-circle") if @item.user.avatar? %></p>
    <p><%=link_to "Количество объявлений #{@item.user.items.size}", '#'%></p>
    <% if current_user && (current_user == @item.user || current_user.admin?) %>
    <p><%= link_to 'Изменить', edit_item_path(@item) %></p>
    <p><%= link_to 'Удалить обьявление', @item, method: :delete, data: { confirm: 'Вы уверены?' } %></p>
    <% if current_user.admin? %>
    <% if @item.user.ban? %>
    <%= link_to 'Разбанить', unban_user_path(@item.user.id), method: :patch, data: { confirm: 'Вы уверены?'}%>
    <% else %>
    <%= link_to 'Забанить', ban_user_path(@item.user.id), method: :patch, data: { confirm: 'Вы уверены?'}%>
    <% end %>
    <% if @item.user.admin? %>
    <p style="padding: 10px">Администратор</p>
    <% else %>
    <%= link_to 'Сделать админом', admin_user_path(@item.user.id), method: :patch, data: { confirm: 'Вы уверены?'}%>
    <% end %>
    <% end %>

    <% end %>
  </div>
</div>


<div class="row">
  <% if @item.attachments? %>
  <% @item.attachments.each do |attachment| %>
  <div class="col-md-8" align="center">
    <%= image_tag(attachment.small_thumb.url) %>
  </div>
  <% end %>
  <% end %>
</div>
<div class="row">
  <p><font size="5">
    <%= @item.description %></font>
  </p>
</div>

</div>