config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }

  resources :messages, only: %i[create]
  get '/messages/new/:id', to: 'messages#new', as: 'new_message'

  authenticate :user do
    get 'new_category', to: 'categories#new', as: 'new_category'
    get 'messages/inbox', to: 'messages#index', as: 'inbox'
    get 'messages/outbox', to: 'messages#index_outbox', as: 'outbox'
    resources :items, only: %i[new create edit update destroy] do
      member do
        patch 'sold'
        patch 'unsold'
      end
    end
    resources :messages, only: %i[index]
    resources :users, only: %i[index]
    patch 'users/:id', to: 'users#change', as: 'admin_change_user'
    resources :categories, only: %i[create]
  end

  resources :items, only: %i[index show]

  resources :messages, only: %i[show]
  resources :categories, only: %i[index], as: 'categories'

  # get 'users/:id', to: 'users#show', as: 'user'

  resources :users, only: %i[show] do
    member do
      patch 'ban'
      patch 'unban'
      patch 'admin'
    end
  end
  get '/categories/*path', to: 'categories#categ_index', param: :path

  root 'items#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li></li>
      <li></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li  style="font-size: 20px; font-weight: 600">
          <%= link_to 'MyWebSite', root_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
       <!-- <li><%= link_to "Home", '#' %></li>
        <li><%= link_to "Help", '#' %></li>-->
        <% if current_user && current_user.admin %>
        <li><%= link_to "Создать категорию", new_category_path %></li>
        <li><%= link_to "Пользователи", users_path %></li>
        <% end %>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Сообщения <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Входящие", inbox_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Отправленные', outbox_path %> </li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Аккаунт <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Мой профиль", current_user %></li>
            <li class="divider"></li>
            <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %> </li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Войти", user_vkontakte_omniauth_authorize_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left">.
        <li><%= link_to 'Создать объявление', new_item_path  %></li>
        <li><%= link_to 'Искать по категориям', categories_path %></li>
      </ul>
    </nav>
  </div>
</header>



app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
  'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
  <%= favicon_link_tag asset_path('favicon.ico') %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
            <%= value %>
      </div>
    <% end %>
    <%= yield %>
 <!--   <%= render 'layouts/footer' %> -->
  </div>
</body>
</html>